todoproject/to_do_app/urls.py
from django.urls import path
from . import views

app_name = "to_do_app"

urlpatterns = [
    path('', views.index, name="index"),
    # path('profile/', views.profile, name="profile"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('add_task/', views.add_task, name="add_task"),
    path('done/<int:id>', views.done, name="done"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('edit/<int:id>', views.edit, name="edit"),

]

todoproject/todoproject/urls.py
from operator import index
from django.contrib import admin
from django.urls import path, include
from to_do_app import views


urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('todos/', include('to_do_app.urls')),
    path('user/', include("user.urls")),
]

todoproject/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),


]

todoproject/to_do_app/models.py
from django.db import models

# Create your models here.

class ToDo(models.Model):
    title = models.CharField(max_length=50, verbose_name = 'Başlıq')
    description = models.TextField(max_length=255, verbose_name = 'Məzmun')
    status = models.BooleanField(default = False)
    finishdate = models.DateTimeField(null=True, blank=True, verbose_name = 'son gün') 
    user = models.ForeignKey("auth.User" , on_delete=models.CASCADE, verbose_name = 'İstifadəçi')

    class Meta:
        ordering = ['status']
    def __str__(self):
        return self.title

todoproject/user/models.py
from django.db import models

# Create your models here.

todoproject/to_do_app/forms.py
from django import forms
from .models import ToDo

class DateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local"

class ToDoForm(forms.ModelForm):
    finishdate = forms.DateTimeField(widget = DateTimeInput)
    class Meta:
        model = ToDo
        fields = ('title', 'description') 

todoproject/user/forms.py
from django import forms

class ProfileForm(forms.Form):
    first_name = forms.CharField(label = 'Ad')
    last_name = forms.CharField(label = 'Soyad')
    email = forms.CharField(label = 'E-post')


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, label="İstifadəçi adı")
    password = forms.CharField(max_length=20, label="Parol", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20, label="Parolu Doğrula", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        confirm = self.cleaned_data.get('confirm')

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parollar Eyni Deyil!")

        values = {
            "username": username,
            "password": password,
            
        }
        return values


class LoginForm(forms.Form):
    username = forms.CharField(label="İstifadəçi adı")
    password = forms.CharField(label="Parol", widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
    }))
    

todoproject/to_do_app/views.py
from django.shortcuts import render,redirect, get_object_or_404,reverse
from sqlalchemy import true

import to_do_app
from .models import ToDo
from django.contrib.auth.decorators import login_required
from .forms import ToDoForm
from django.contrib import messages
# Create your views here.


@login_required(login_url='user:login')
def index(request):
    todos = ToDo.objects.filter(user = request.user)
    context = {
        "todos" :todos,
    }
    return render (request, "index.html", context)

@login_required(login_url='user:login')
def done(request,id):
    todo = ToDo.objects.filter(id = id).first()
    todo.status = not True
    todo.save()
    return redirect('to_do_app:index')


@login_required(login_url='user:login')
def detail(request,id):
    todo = ToDo.objects.filter(id = id).first()
    context = {
        'todo': todo,
    }
    return render(request, 'detail.html',context)
    
@login_required(login_url='user:login')
def edit(request, id):
    todo = get_object_or_404(ToDo, id=id)
    form = ToDoForm(request.POST or None,  instance = todo )
    # initial = {'finishdate': todo.finishdate}
    # form = ToDoForm(initial=initial)

 
    if form.is_valid():
        todo = form.save(commit=False)
        todo.user = request.user
        todo.finishdate = request.POST.get('finishdate')
        todo.save()
        messages.success(request, "Task Redaktə Edildi")
        return redirect(reverse('to_do_app:detail', kwargs={'id':id}))
    context={
        "form":form,
    }
    return render(request, 'edit.html', context)

@login_required(login_url='user:login')
def add_task(request):
    form = ToDoForm(request.POST or None)
    context={
        "form":form,
    }



    if form.is_valid():
        todo = form.save(commit = False)
        todo.finishdate = request.POST.get('finishdate')
        todo.user = request.user
        todo.save()
        
        messages.success(request, "Task Əlavə Edildi")

    return render(request, "add_task.html", context)
def  delete(request,id):
    todo = get_object_or_404(ToDo, id = id)
    todo.delete()
    return redirect('to_do_app:index')

todoproject/user/views.py
from ast import Pass
from django.shortcuts import get_object_or_404, render, redirect
from .forms import LoginForm, RegisterForm , ProfileForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout

def profile (request):
    form = ProfileForm(request.POST or None)
    if form.is_valid():
        username = request.user.username
        user = get_object_or_404(User, username = username)
    #  ilk IKI  SETRIN BASQA vARIANTI  user = get_object_or_404(User, username = request.user.username)
    context = {
        "form": form,
    }
    return render(request, 'profile.html',context)

def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        new_user = User(username=username)
        new_user.set_password(password)
        new_user.save()
        
        login(request, new_user)
        messages.success(request, "Qeydiyyatdan keçdiniz!")
        return redirect('to_do_app:index')

    context = {
        "form": form,
    }
    return render(request, "register.html", context)

def login_user(request):
    form = LoginForm(request.POST or None)
    
    context = {
        "form": form,
    }

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user=authenticate(username=username, password=password)
    
        if user is None:
            messages.warning(request, "İstifadəçi adı və ya parol səhvdir")
            return render(request, "login.html", context)

        messages.success(request, "Sayta giriş etdiniz")
        login(request, user)
        return redirect('to_do_app:index')

    return render(request, "login.html", context)
    

def logout_user(request):
    logout(request)
    messages.warning(request, "Saytdan çıxış etdiniz")
    return redirect('to_do_app:index')
    

todoproject/templates/add_task.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3> Post Əlavə Et </h3>
    <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form | crispy}}
            <br>
            <button type="submit" class="btn btn-primary">Əlavə Et</button>
        </form>
    </div>
</div>
{% endblock body %}

todoproject/templates/detail.html
{% extends "layout.html" %}

{% block body %}

<!-- {{todo.id}}
{{todo.title}}
{{todo.description}}
{{todo.status}}
{{todo.finishdate}}
{{todo.user}} -->

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Basliq</th>
        <th scope="col">Aciqlama</th>
        <th scope="col">Status</th>
        <th scope="col">Son gun</th>
        <th scope="col">User</th>
        

      </tr>
    </thead>
    <tbody>
      
      <tr>
        <th scope="row">
          {{todo.id}}
        </th>
        <td >
            {{todo.title}}
        </td>
        <td >
          {{todo.description}}
        </td>
        <td>
          {{todo.status}}
        </td>
      
        <td>
            {{todo.finishdate}}
        </td>
        <td>
          {{todo.user}}
        </td>
      </tr>
    </tbody>
  </table>
{% endblock body %}

todoproject/templates/edit.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3> Task Redaktə Et </h3>
    <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form | crispy}}
            <br>
            <button type="submit" class="btn btn-primary">Əlavə Et</button>
        </form>
    </div>
</div>
{% endblock body %}

todoproject/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">İKT-LAB</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'to_do_app:index' %}">Əsas Səhifə</a>
          </li>
          
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/user/profile">Profil</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/user/logout">Çıxış</a>
          </li>
          
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/user/register">Qeydiyyatdan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/user/login">Giriş</a>
          </li>
          {% endif %}
        </ul>
       </div>
    </div>
  </nav>

todoproject/templates/index.html
{% extends "layout.html" %}

{% block body %}


<p> Xoş gəldiniz <small>{{ request.user.username }}<small></p>
<hr>
<a href="{% url 'to_do_app:add_task'%}" class="btn btn-primary">Task Əlavə Et</a>
<hr>

{% if todos %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Başlıq</th>
                <th scope="col">Bitis tarixi</th>
                <th scope="col">Status</th>
                <th scope="col">Əməliyyatlar</th>
            </tr>
            </thead>
            <tbody>
            {% for todo in todos %}
                <tr>
                    <th scope="row">{{to.id}}</th>
                    <td> <a href="{% url 'to_do_app:detail' todo.id %}">{{todo.title}}</a></td>
                    <td>{{todo.finishdate}}</td>
                    <td>{{todo.status}}</td>

                    <td><a href="{% url 'to_do_app:done' todo.id %}" class="btn btn-success">Tamamlandi</a></td>
                    <td><a href="{% url 'to_do_app:edit' todo.id %}" class="btn btn-primary">Redakte et</a></td>
                    <td><a href="{% url 'to_do_app:delete' todo.id %}" class="btn btn-danger">Sil</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

{% else %}
    <div class="alert alert-danger">
        Hələ ki task qeyd edilməyib 
    </div>
{% endif %}

{% endblock body %}

todoproject/templates/layout.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% include "includes/navbar.html" %}
    <div class="container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div{% if message.tags %} class="alert alert-{{ message.tags }} container"{% endif %}>{{ message }}</div>
                {% endfor %}
            </ul>
        {% endif %}
        {% block body %}
        
        {% endblock body %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

todoproject/templates/login.html
{% extends 'layout.html' %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3> Giriş </h3>
    <hr>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <br>
            <button type="submit" class="btn btn-primary">Giriş Et</button>
        </form>
    </div>
</div>


{% endblock body %}

todoproject/templates/profile.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3> Profil  </h3>
    <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form | crispy}}
            <br>
            <button type="submit" class="btn btn-primary">Yadda saxla</button>
        </form>
    </div>
</div>
{% endblock body %}

todoproject/templates/register.html
{% extends 'layout.html' %}
{% block body %}



<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3> Qeydiyyat </h3>
    <hr>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <br>
            <button type="submit" class="btn btn-primary">Qeydiyyatdan keç</button>
        </form>
    </div>
</div>
{% endblock body %}